model = "gpt-5.5"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
approvals_reviewer = "user"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.react-aria]
command = "npx"
args = ["@react-aria/mcp@latest"]

[mcp_servers.sentry]
url = "https://mcp.sentry.dev/mcp"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.context7]
type = "http"
url = "https://mcp.context7.com/mcp"

env_http_headers = { CONTEXT7_API_KEY = "CONTEXT7_API_KEY" }

[mcp_servers.uidotsh]
url = "https://ui.sh/mcp?agent=codex"
env_http_headers = { Authorization = "UIDOTSH_MCP_AUTHORIZATION" }

[mcp_servers.uidotsh.tools.uidotsh_fetch]
approval_mode = "approve"

[features]
goals = true
multi_agent = true
prevent_idle_sleep = true
terminal_resize_reflow = true
memories = true
external_migration = true

[plugins."github@openai-curated"]
enabled = true

[plugins."sentry@openai-curated"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."vercel@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-05-16T08:10:12Z"
source_type = "local"
source = "/Users/christofferbergj/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-16T09:01:39Z"
source_type = "local"
source = "/Users/christofferbergj/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[projects."/Users/christofferbergj/code/andel-energi"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/Users/christofferbergj/code/fysioscout-web"]
trust_level = "trusted"

[projects."/Users/christofferbergj/code/andel-energi-assets"]
trust_level = "trusted"

[projects."/Users/christofferbergj/code/aure"]
trust_level = "trusted"

[projects."/Users/christofferbergj/Documents/Codex/2026-05-08/use-yadm-status-to-check-my"]
trust_level = "trusted"

[projects."/Users/christofferbergj/code/balder-web"]
trust_level = "trusted"

[projects."/Users/christofferbergj/code/sweco-web"]
trust_level = "trusted"

[projects."/Users/christofferbergj/code/vpt"]
trust_level = "trusted"

[projects."/Users/christofferbergj/code/retur-web"]
trust_level = "trusted"

[projects."/Users/christofferbergj/Documents/Codex/2026-05-16/i-have-just-set-up-context7"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[notice]
hide_full_access_warning = true

[tui]
notification_condition = "always"
