#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xffd65d0e
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

# Label spaces
yabai -m space 1 --label main
yabai -m space 2 --label editor
yabai -m space 3 --label messages
yabai -m space 4 --label media
yabai -m space 5 --label notes
yabai -m space 6 --label mail
yabai -m space 7 --label figma
yabai -m space 8 --label other

# App rules
yabai -m rule --add app="^Google Chrome$" space="main" 
yabai -m rule --add app="^WebStorm$" space="editor" manage=off
yabai -m rule --add app="^WebStorm$" title="( – )" space="editor" manage=on
yabai -m rule --add app="^Slack$" space="messages"
yabai -m rule --add app="^Notion$" space="notes"
yabai -m rule --add app="^Todoist$" space="notes"
yabai -m rule --add app="^Spotify$" space="media" 
yabai -m rule --add app="^Sonos$" space="media" 
yabai -m rule --add app="^Podcasts$" space="media" 
yabai -m rule --add app="^Messenger$" space="messages"
yabai -m rule --add app="^Spark$" space="mail"
yabai -m rule --add app="^Spark$" title="^New Message$" space="mail" manage=off
yabai -m rule --add app="^Figma$" monitor=2 space="figma"

# Apps to not manage
yabai -m rule --add app="^CleanShot X$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^AltTab$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="^Hidden Bar$" manage=off
yabai -m rule --add app="^Homerow$" manage=off
yabai -m rule --add app="^Rocket$" manage=off
yabai -m rule --add app="^Vimac$" manage=off
yabai -m rule --add app="^MonitorControl$" manage=off

echo "yabai configuration loaded.."
