#!/usr/bin/env sh
#
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# yabai -m signal --add event=display_added action="sleep 2 && fish -c yabai_init_spaces"
# yabai -m signal --add event=display_removed action="sleep 2 && fish -c yabai_init_spaces"

# General settings
yabai -m config active_window_opacity 1.0
yabai -m config auto_balance off
yabai -m config display_arrangement_order default
yabai -m config external_bar off:40:0
yabai -m config focus_follows_mouse off
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config menubar_opacity 1.0
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier fn
yabai -m config normal_window_opacity 0.95
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_shadow float
yabai -m config window_zoom_persist on

# Animation
yabai -m config window_animation_duration 0.0
yabai -m config window_animation_easing ease_out_circ

# General space settings
yabai -m config layout bsp
yabai -m config bottom_padding 16
yabai -m config left_padding 16
yabai -m config right_padding 16
yabai -m config top_padding 16
yabai -m config window_gap 16

# Run Yabai init script
fish -c init_yabai
