[tools]
bun = "latest"
node = "lts"
pnpm = "11"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[tasks.update-all]
description = "Update Homebrew, Mise tools, and Bun globals"
run = [
    "brew upgrade",
    "brew cleanup",
    "brew autoremove",
    "mise upgrade",
    "mise prune -y",
    "pnx skills update -y -g",
    "pnpm update --global --latest",
]
